// Mock data for the dashboard
import type { CurriculumTracking } from '@/types/tracking'
import type { User, UserStats } from '@/types/user-management'
import type { Notification } from '@/types/notifications'
import type { AuditLog, AuditLogsStats } from '@/types/audit-logs'

export const mockUsers: User[] = [
  {
    id: 1,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@must.ac.ke',
    username: 'jane_smith',
    phoneNumber: '+254712345678',
    roles: ['ADMIN', 'DEAN'],
    status: 'active',
    department: 'Computing & Informatics',
    avatar: 'JS',
    createdAt: '2023-01-15T10:30:00Z',
    updatedAt: '2024-03-10T14:22:00Z',
  },
  {
    id: 2,
    firstName: 'James',
    lastName: 'Mwaliko',
    email: 'james.mwaliko@must.ac.ke',
    username: 'james_mwaliko',
    phoneNumber: '+254787654321',
    roles: ['DEAN', 'QA'],
    status: 'active',
    department: 'Engineering',
    avatar: 'JM',
    createdAt: '2023-02-20T09:15:00Z',
    updatedAt: '2024-03-08T11:45:00Z',
  },
  {
    id: 3,
    firstName: 'Grace',
    lastName: 'Muthoni',
    email: 'grace.muthoni@must.ac.ke',
    username: 'grace_muthoni',
    phoneNumber: '+254723456789',
    roles: ['DEPT_REP'],
    status: 'active',
    department: 'Computing & Informatics',
    avatar: 'GM',
    createdAt: '2023-03-10T13:20:00Z',
    updatedAt: '2024-03-09T16:30:00Z',
  },
  {
    id: 4,
    firstName: 'Peter',
    lastName: 'Kariuki',
    email: 'peter.kariuki@must.ac.ke',
    username: 'peter_kariuki',
    phoneNumber: '+254734567890',
    roles: ['QA'],
    status: 'active',
    department: 'Quality Assurance',
    avatar: 'PK',
    createdAt: '2023-04-05T08:45:00Z',
    updatedAt: '2024-03-07T10:15:00Z',
  },
  {
    id: 5,
    firstName: 'Susan',
    lastName: 'Kipchoge',
    email: 'susan.kipchoge@must.ac.ke',
    username: 'susan_kipchoge',
    phoneNumber: '+254745678901',
    roles: ['SENATE'],
    status: 'active',
    department: 'Academic Affairs',
    avatar: 'SK',
    createdAt: '2023-05-12T11:30:00Z',
    updatedAt: '2024-03-06T15:50:00Z',
  },
  {
    id: 6,
    firstName: 'David',
    lastName: 'Kiplagat',
    email: 'david.kiplagat@must.ac.ke',
    username: 'david_kiplagat',
    phoneNumber: '+254756789012',
    roles: ['DEPT_REP'],
    status: 'active',
    department: 'Engineering',
    avatar: 'DK',
    createdAt: '2023-06-18T14:15:00Z',
    updatedAt: '2024-03-05T09:20:00Z',
  },
  {
    id: 7,
    firstName: 'Mary',
    lastName: 'Wanjiru',
    email: 'mary.wanjiru@must.ac.ke',
    username: 'mary_wanjiru',
    phoneNumber: '+254767890123',
    roles: ['STAFF'],
    status: 'active',
    department: 'Administration',
    avatar: 'MW',
    createdAt: '2023-07-22T10:00:00Z',
    updatedAt: '2024-03-04T12:30:00Z',
  },
  {
    id: 8,
    firstName: 'Daniel',
    lastName: 'Mutua',
    email: 'daniel.mutua@must.ac.ke',
    username: 'daniel_mutua',
    phoneNumber: '+254778901234',
    roles: ['QA', 'DEPT_REP'],
    status: 'active',
    department: 'Computing & Informatics',
    avatar: 'DM',
    createdAt: '2023-08-30T15:45:00Z',
    updatedAt: '2024-03-03T13:15:00Z',
  },
  {
    id: 9,
    firstName: 'Catherine',
    lastName: 'Omondi',
    email: 'catherine.omondi@must.ac.ke',
    username: 'catherine_omondi',
    phoneNumber: '+254789012345',
    roles: ['DEAN'],
    status: 'active',
    department: 'Business & Economics',
    avatar: 'CO',
    createdAt: '2023-09-14T09:30:00Z',
    updatedAt: '2024-03-02T14:45:00Z',
  },
  {
    id: 10,
    firstName: 'Michael',
    lastName: 'Ng\'ethe',
    email: 'michael.ngethe@must.ac.ke',
    username: 'michael_ngethe',
    phoneNumber: '+254790123456',
    roles: ['DEPT_REP'],
    status: 'pending',
    department: 'Natural Sciences',
    avatar: 'MN',
    createdAt: '2024-03-15T11:20:00Z',
    updatedAt: '2024-03-15T11:20:00Z',
  },
  {
    id: 11,
    firstName: 'Alice',
    lastName: 'Koech',
    email: 'alice.koech@must.ac.ke',
    username: 'alice_koech',
    phoneNumber: '+254701234567',
    roles: ['STAFF'],
    status: 'inactive',
    department: 'Administration',
    avatar: 'AK',
    createdAt: '2023-10-20T12:00:00Z',
    updatedAt: '2024-02-28T10:00:00Z',
  },
  {
    id: 12,
    firstName: 'Robert',
    lastName: 'Kemboi',
    email: 'robert.kemboi@must.ac.ke',
    username: 'robert_kemboi',
    phoneNumber: '+254712345679',
    roles: ['ADMIN'],
    status: 'active',
    department: 'Information Technology',
    avatar: 'RK',
    createdAt: '2023-11-05T16:30:00Z',
    updatedAt: '2024-03-01T11:15:00Z',
  },
  {
    id: 13,
    firstName: 'Victoria',
    lastName: 'Kipkemboi',
    email: 'victoria.kipkemboi@must.ac.ke',
    username: 'victoria_kipkemboi',
    phoneNumber: '+254723456790',
    roles: ['QA'],
    status: 'active',
    department: 'Quality Assurance',
    avatar: 'VK',
    createdAt: '2023-12-10T13:45:00Z',
    updatedAt: '2024-03-11T15:30:00Z',
  },
  {
    id: 14,
    firstName: 'Samuel',
    lastName: 'Kipyegon',
    email: 'samuel.kipyegon@must.ac.ke',
    username: 'samuel_kipyegon',
    phoneNumber: '+254734567891',
    roles: ['DEPT_REP'],
    status: 'active',
    department: 'Engineering',
    avatar: 'SK',
    createdAt: '2024-01-08T10:15:00Z',
    updatedAt: '2024-03-12T09:45:00Z',
  },
  {
    id: 15,
    firstName: 'Rachel',
    lastName: 'Mwangi',
    email: 'rachel.mwangi@must.ac.ke',
    username: 'rachel_mwangi',
    phoneNumber: '+254745678902',
    roles: ['SENATE'],
    status: 'active',
    department: 'Academic Affairs',
    avatar: 'RM',
    createdAt: '2024-01-20T14:30:00Z',
    updatedAt: '2024-03-10T12:00:00Z',
  },
]

export const mockUserStats: UserStats = {
  totalUsers: mockUsers.length,
  activeUsers: mockUsers.filter((u) => u.status === 'active').length,
  deans: mockUsers.filter((u) => u.roles.includes('DEAN')).length,
  pendingAccess: mockUsers.filter((u) => u.status === 'pending').length,
}

export const mockDashboardData = {
  stats: {
    totalCurricula: 247,
    totalSchools: 8,
    totalPrograms: 24,
    totalDepartments: 72,
  },
  schools: [
    {
      id: 'computing',
      name: 'Computing & Informatics',
      departments: 8,
      total: 45,
      programs: [
        {
          id: 'masters-computing',
          name: "Master's",
          type: 'masters',
          count: 12,
          departments: [
            {
              name: 'Computer Science',
              curricula: [
                {
                  id: 'msc-cs-se',
                  title: 'MSc Computer Science - Software Engineering',
                  status: 'approved',
                  lastUpdated: '2024-01-15',
                },
                {
                  id: 'msc-cs-ai',
                  title: 'MSc Computer Science - Artificial Intelligence',
                  status: 'approved',
                  lastUpdated: '2024-01-10',
                },
                {
                  id: 'msc-cs-cyber',
                  title: 'MSc Computer Science - Cybersecurity',
                  status: 'pending',
                  lastUpdated: '2024-01-20',
                },
              ],
            },
            {
              name: 'Information Technology',
              curricula: [
                {
                  id: 'msc-it-net',
                  title: 'MSc Information Technology - Network Security',
                  status: 'approved',
                  lastUpdated: '2024-01-08',
                },
              ],
            },
          ],
        },
        {
          id: 'degree-computing',
          name: "Bachelor's",
          type: 'degree',
          count: 28,
          departments: [
            {
              name: 'Computer Science',
              curricula: [
                {
                  id: 'bcs',
                  title: 'Bachelor of Computer Science',
                  status: 'approved',
                  lastUpdated: '2024-01-05',
                },
                {
                  id: 'bse',
                  title: 'Bachelor of Software Engineering',
                  status: 'approved',
                  lastUpdated: '2024-01-07',
                },
              ],
            },
          ],
        },
        {
          id: 'phd-computing',
          name: 'PhD',
          type: 'phd',
          count: 5,
          departments: [
            {
              name: 'Computer Science',
              curricula: [
                {
                  id: 'phd-cs',
                  title: 'PhD in Computer Science',
                  status: 'approved',
                  lastUpdated: '2024-01-03',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'agriculture',
      name: 'Agriculture & Food Science',
      departments: 6,
      total: 42,
      programs: [
        {
          id: 'masters-agriculture',
          name: "Master's",
          type: 'masters',
          count: 15,
          departments: [
            {
              name: 'Agricultural Economics',
              curricula: [
                {
                  id: 'msc-agric-farm',
                  title: 'MSc Agricultural Economics - Farm Management',
                  status: 'approved',
                  lastUpdated: '2024-01-12',
                },
              ],
            },
          ],
        },
        {
          id: 'degree-agriculture',
          name: "Bachelor's",
          type: 'degree',
          count: 21,
          departments: [
            {
              name: 'Agricultural Economics',
              curricula: [
                {
                  id: 'bagric-econ',
                  title: 'Bachelor of Agricultural Economics',
                  status: 'approved',
                  lastUpdated: '2024-01-06',
                },
              ],
            },
          ],
        },
        {
          id: 'phd-agriculture',
          name: 'PhD',
          type: 'phd',
          count: 6,
          departments: [
            {
              name: 'Agricultural Economics',
              curricula: [
                {
                  id: 'phd-agric-econ',
                  title: 'PhD in Agricultural Economics',
                  status: 'pending',
                  lastUpdated: '2024-01-22',
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'engineering',
      name: 'Engineering & Technology',
      departments: 5,
      total: 38,
      programs: [
        {
          id: 'masters-engineering',
          name: "Master's",
          type: 'masters',
          count: 12,
          departments: [
            {
              name: 'Civil Engineering',
              curricula: [
                {
                  id: 'msc-civil-struct',
                  title: 'MSc Civil Engineering - Structural',
                  status: 'approved',
                  lastUpdated: '2024-01-11',
                },
              ],
            },
          ],
        },
        {
          id: 'degree-engineering',
          name: "Bachelor's",
          type: 'degree',
          count: 22,
          departments: [
            {
              name: 'Civil Engineering',
              curricula: [
                {
                  id: 'bcivil',
                  title: 'Bachelor of Civil Engineering',
                  status: 'approved',
                  lastUpdated: '2024-01-04',
                },
              ],
            },
          ],
        },
        {
          id: 'phd-engineering',
          name: 'PhD',
          type: 'phd',
          count: 4,
          departments: [
            {
              name: 'Civil Engineering',
              curricula: [
                {
                  id: 'phd-civil',
                  title: 'PhD in Civil Engineering',
                  status: 'review',
                  lastUpdated: '2024-01-21',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}

export const mockCurriculaData = {
  curricula: [
    {
      id: 1,
      title: 'MSc Computer Science - Software Engineering',
      school: 'Computing & Informatics',
      department: 'Computer Science',
      status: 'approved',
      lastUpdated: '2024-01-15',
    },
    {
      id: 2,
      title: 'MSc Computer Science - Artificial Intelligence',
      school: 'Computing & Informatics',
      department: 'Computer Science',
      status: 'approved',
      lastUpdated: '2024-01-10',
    },
    {
      id: 3,
      title: 'MSc Computer Science - Cybersecurity',
      school: 'Computing & Informatics',
      department: 'Computer Science',
      status: 'pending',
      lastUpdated: '2024-01-20',
    },
    {
      id: 4,
      title: 'Bachelor of Computer Science',
      school: 'Computing & Informatics',
      department: 'Computer Science',
      status: 'approved',
      lastUpdated: '2024-01-05',
    },
    {
      id: 5,
      title: 'Bachelor of Software Engineering',
      school: 'Computing & Informatics',
      department: 'Computer Science',
      status: 'approved',
      lastUpdated: '2024-01-07',
    },
    {
      id: 6,
      title: 'PhD in Computer Science',
      school: 'Computing & Informatics',
      department: 'Computer Science',
      status: 'approved',
      lastUpdated: '2024-01-03',
    },
    {
      id: 7,
      title: 'MSc Agricultural Economics - Farm Management',
      school: 'Agriculture & Food Science',
      department: 'Agricultural Economics',
      status: 'approved',
      lastUpdated: '2024-01-12',
    },
    {
      id: 8,
      title: 'Bachelor of Agricultural Economics',
      school: 'Agriculture & Food Science',
      department: 'Agricultural Economics',
      status: 'approved',
      lastUpdated: '2024-01-06',
    },
    {
      id: 9,
      title: 'PhD in Agricultural Economics',
      school: 'Agriculture & Food Science',
      department: 'Agricultural Economics',
      status: 'pending',
      lastUpdated: '2024-01-22',
    },
    {
      id: 10,
      title: 'MSc Civil Engineering - Structural',
      school: 'Engineering & Technology',
      department: 'Civil Engineering',
      status: 'approved',
      lastUpdated: '2024-01-11',
    },
    {
      id: 11,
      title: 'Bachelor of Civil Engineering',
      school: 'Engineering & Technology',
      department: 'Civil Engineering',
      status: 'approved',
      lastUpdated: '2024-01-04',
    },
    {
      id: 12,
      title: 'PhD in Civil Engineering',
      school: 'Engineering & Technology',
      department: 'Civil Engineering',
      status: 'review',
      lastUpdated: '2024-01-21',
    },
  ],
}

// Admin-compatible mock data derived from existing mock data
export const mockAdminCurricula = mockCurriculaData.curricula.map((c) => {
  const schoolEntry = mockDashboardData.schools.find((s) => s.name === c.school)
  const programEntry = schoolEntry?.programs.find((p) =>
    p.departments.some((d) => d.curricula.some((cur) => cur.title === c.title))
  )
  return {
    id: String(c.id),
    title: c.title,
    code: c.title
      .split(' ')
      .map((w) => w[0])
      .join('')
      .toUpperCase()
      .slice(0, 8),
    status: c.status as 'approved' | 'pending' | 'draft' | 'rejected' | 'under_review',
    schoolId: schoolEntry?.id ?? '',
    schoolName: c.school,
    programId: programEntry?.id ?? '',
    programName: programEntry?.name ?? '',
    department: c.department,
    lastModified: c.lastUpdated,
    createdDate: c.lastUpdated,
    effectiveDate: c.lastUpdated,
    enrollments: Math.floor(Math.random() * 200) + 20,
  }
})

export const mockAdminSchools = mockDashboardData.schools.map((s) => ({
  id: s.id,
  name: s.name,
}))

export const mockAdminPrograms = mockDashboardData.schools.flatMap((s) =>
  s.programs.map((p) => ({
    id: p.id,
    name: p.name,
  }))
)

export const mockAdminStats = {
  total: mockCurriculaData.curricula.length,
  approved: mockCurriculaData.curricula.filter((c) => c.status === 'approved').length,
  pending: mockCurriculaData.curricula.filter((c) => c.status === 'pending').length,
  rejected: mockCurriculaData.curricula.filter((c) => c.status === 'rejected').length,
  draft: mockCurriculaData.curricula.filter((c) => c.status === 'draft').length,
  underReview: mockCurriculaData.curricula.filter((c) => c.status === 'under_review').length,
}

export const mockAnalyticsData = {
  summaryStats: [
    { value: '85%', label: 'Approval Rate' },
    { value: '24', label: 'Avg. Review Days' },
    { value: '95%', label: 'Quality Score' },
  ],
  chartData: [
    { school: 'Computing & Informatics', count: 45, color: '#00D666' },
    { school: 'Agriculture & Food Science', count: 42, color: '#f0b41c' },
    { school: 'Engineering & Technology', count: 38, color: '#1a3a6e' },
  ],
  recentActivity: [
    '5 new curricula submitted this week',
    '12 curricula approved in the last 7 days',
    '3 curricula pending review',
  ],
  topSchools: [
    { school: 'Computing & Informatics', count: 45, color: '#00D666' },
    { school: 'Agriculture & Food Science', count: 42, color: '#f0b41c' },
    { school: 'Engineering & Technology', count: 38, color: '#1a3a6e' },
  ],
}

// Mock data for curriculum tracking
export const mockCurriculumTrackingData: CurriculumTracking[] = [
  {
    id: 'track-001',
    trackingId: 'TRK-2024-001',
    title: 'MSc Computer Science - Software Engineering',
    displayTitle: 'MSc Computer Science - Software Engineering',
    displayCode: 'MSCSE',
    proposedCurriculumName: 'MSc Computer Science - Software Engineering',
    proposedCurriculumCode: 'MSCSE',
    proposedDurationSemesters: 4,
    curriculumDescription: 'Advanced software engineering program focusing on modern development practices',
    school: 'Computing & Informatics',
    schoolName: 'Computing & Informatics',
    schoolId: 1,
    department: 'Computer Science',
    departmentName: 'Computer Science',
    departmentId: 101,
    academicLevel: 'Masters',
    currentStage: 'dean_committee',
    currentStageDisplayName: 'Dean Committee',
    status: 'in_progress',
    statusDisplayName: 'In Progress',
    priority: 'high',
    isActive: true,
    isCompleted: false,
    daysInCurrentStage: 5,
    totalDays: 18,
    initiatedByName: 'Dr. Jane Smith',
    initiatedByEmail: 'jane.smith@must.ac.tz',
    currentAssigneeName: 'Prof. John Doe',
    currentAssigneeEmail: 'john.doe@must.ac.tz',
    submittedDate: '2024-03-01',
    lastUpdated: '2024-03-13',
    expectedCompletionDate: '2024-04-15',
    proposedEffectiveDate: '2024-09-01',
    proposedExpiryDate: '2027-08-31',
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-03-13T14:30:00Z',
    initialNotes: 'New software engineering specialization track',
    stages: {
      department_submission: {
        status: 'completed',
        assignedTo: 'Dr. Jane Smith',
        startedDate: '2024-03-01',
        completedDate: '2024-03-03',
        notes: 'Initial submission approved',
        documents: [
          {
            id: 'doc-001',
            originalFilename: 'curriculum_proposal.pdf',
            contentType: 'application/pdf',
            fileSize: 2048576,
            formattedFileSize: '2.0 MB',
            documentType: 'proposal',
            documentTypeDisplayName: 'Curriculum Proposal',
            uploadedByName: 'Dr. Jane Smith',
            uploadedAt: '2024-03-01T08:15:00Z',
            uploadedAtFormatted: 'Mar 1, 2024 8:15 AM',
          },
        ],
      },
      school_board_review: {
        status: 'completed',
        assignedTo: 'School Board',
        startedDate: '2024-03-03',
        completedDate: '2024-03-08',
        notes: 'Approved with minor revisions',
        documents: [
          {
            id: 'doc-002',
            originalFilename: 'board_review_feedback.pdf',
            contentType: 'application/pdf',
            fileSize: 1024000,
            formattedFileSize: '1.0 MB',
            documentType: 'feedback',
            documentTypeDisplayName: 'Review Feedback',
            uploadedByName: 'School Board',
            uploadedAt: '2024-03-08T10:00:00Z',
            uploadedAtFormatted: 'Mar 8, 2024 10:00 AM',
          },
        ],
      },
      dean_committee: {
        status: 'in_progress',
        assignedTo: 'Prof. John Doe',
        startedDate: '2024-03-08',
        notes: 'Currently under review by Dean committee',
      },
      senate_review: {
        status: 'pending',
      },
      quality_assurance: {
        status: 'pending',
      },
      cue_submission: {
        status: 'pending',
      },
      cue_review: {
        status: 'pending',
      },
      final_approval: {
        status: 'pending',
      },
    },
  },
  {
    id: 'track-002',
    trackingId: 'TRK-2024-002',
    title: 'Bachelor of Agricultural Economics',
    displayTitle: 'Bachelor of Agricultural Economics',
    displayCode: 'BAGEC',
    proposedCurriculumName: 'Bachelor of Agricultural Economics',
    proposedCurriculumCode: 'BAGEC',
    proposedDurationSemesters: 8,
    curriculumDescription: 'Comprehensive program in agricultural economics and farm management',
    school: 'Agriculture & Food Science',
    schoolName: 'Agriculture & Food Science',
    schoolId: 2,
    department: 'Agricultural Economics',
    departmentName: 'Agricultural Economics',
    departmentId: 201,
    academicLevel: 'Undergraduate',
    currentStage: 'school_board_review',
    currentStageDisplayName: 'School Board Review',
    status: 'in_progress',
    statusDisplayName: 'In Progress',
    priority: 'medium',
    isActive: true,
    isCompleted: false,
    daysInCurrentStage: 12,
    totalDays: 12,
    initiatedByName: 'Prof. James Mwaliko',
    initiatedByEmail: 'james.mwaliko@must.ac.tz',
    currentAssigneeName: 'School Board Review Panel',
    currentAssigneeEmail: 'schoolboard@must.ac.tz',
    submittedDate: '2024-03-01',
    lastUpdated: '2024-03-13',
    expectedCompletionDate: '2024-05-01',
    proposedEffectiveDate: '2024-09-01',
    proposedExpiryDate: '2028-08-31',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-03-13T16:45:00Z',
    initialNotes: 'Updated curriculum to reflect industry changes',
    stages: {
      department_submission: {
        status: 'completed',
        assignedTo: 'Prof. James Mwaliko',
        startedDate: '2024-03-01',
        completedDate: '2024-03-01',
        notes: 'Submitted by department head',
        documents: [
          {
            id: 'doc-003',
            originalFilename: 'agric_economics_curriculum.pdf',
            contentType: 'application/pdf',
            fileSize: 3145728,
            formattedFileSize: '3.0 MB',
            documentType: 'proposal',
            documentTypeDisplayName: 'Curriculum Proposal',
            uploadedByName: 'Prof. James Mwaliko',
            uploadedAt: '2024-03-01T09:30:00Z',
            uploadedAtFormatted: 'Mar 1, 2024 9:30 AM',
          },
        ],
      },
      school_board_review: {
        status: 'in_progress',
        assignedTo: 'School Board Review Panel',
        startedDate: '2024-03-01',
        notes: 'Under review',
      },
      dean_committee: {
        status: 'pending',
      },
      senate_review: {
        status: 'pending',
      },
      quality_assurance: {
        status: 'pending',
      },
      cue_submission: {
        status: 'pending',
      },
      cue_review: {
        status: 'pending',
      },
      final_approval: {
        status: 'pending',
      },
    },
  },
  {
    id: 'track-003',
    trackingId: 'TRK-2024-003',
    title: 'PhD in Civil Engineering',
    displayTitle: 'PhD in Civil Engineering',
    displayCode: 'PHCE',
    proposedCurriculumName: 'PhD in Civil Engineering',
    proposedCurriculumCode: 'PHCE',
    proposedDurationSemesters: 6,
    curriculumDescription: 'Doctoral research program in advanced civil engineering',
    school: 'Engineering & Technology',
    schoolName: 'Engineering & Technology',
    schoolId: 3,
    department: 'Civil Engineering',
    departmentName: 'Civil Engineering',
    departmentId: 301,
    academicLevel: 'Doctoral',
    currentStage: 'quality_assurance',
    currentStageDisplayName: 'Quality Assurance',
    status: 'on_hold',
    statusDisplayName: 'On Hold',
    priority: 'low',
    isActive: true,
    isCompleted: false,
    daysInCurrentStage: 8,
    totalDays: 42,
    initiatedByName: 'Dr. Peter Kipchoge',
    initiatedByEmail: 'peter.kipchoge@must.ac.tz',
    currentAssigneeName: 'Quality Assurance Officer',
    currentAssigneeEmail: 'qa@must.ac.tz',
    submittedDate: '2024-02-15',
    lastUpdated: '2024-03-10',
    expectedCompletionDate: '2024-06-01',
    proposedEffectiveDate: '2024-09-01',
    proposedExpiryDate: '2029-08-31',
    createdAt: '2024-02-15T10:00:00Z',
    updatedAt: '2024-03-10T11:20:00Z',
    initialNotes: 'On hold pending clarification on research focus areas',
    stages: {
      department_submission: {
        status: 'completed',
        assignedTo: 'Dr. Peter Kipchoge',
        startedDate: '2024-02-15',
        completedDate: '2024-02-16',
        feedback: 'Well-structured proposal',
      },
      school_board_review: {
        status: 'completed',
        assignedTo: 'School Board',
        startedDate: '2024-02-16',
        completedDate: '2024-02-20',
        feedback: 'Approved for further review',
      },
      dean_committee: {
        status: 'completed',
        assignedTo: 'Dean Committee',
        startedDate: '2024-02-20',
        completedDate: '2024-02-28',
        notes: 'Approved with conditions',
      },
      senate_review: {
        status: 'completed',
        assignedTo: 'Senate',
        startedDate: '2024-02-28',
        completedDate: '2024-03-05',
      },
      quality_assurance: {
        status: 'in_progress',
        assignedTo: 'Quality Assurance Officer',
        startedDate: '2024-03-05',
        notes: 'Awaiting additional documentation',
      },
      cue_submission: {
        status: 'pending',
      },
      cue_review: {
        status: 'pending',
      },
      final_approval: {
        status: 'pending',
      },
    },
  },
  {
    id: 'track-004',
    trackingId: 'TRK-2024-004',
    title: 'MSc Computer Science - Artificial Intelligence',
    displayTitle: 'MSc Computer Science - Artificial Intelligence',
    displayCode: 'MSCAI',
    proposedCurriculumName: 'MSc Computer Science - Artificial Intelligence',
    proposedCurriculumCode: 'MSCAI',
    proposedDurationSemesters: 4,
    curriculumDescription: 'Specialized master program in artificial intelligence and machine learning',
    school: 'Computing & Informatics',
    schoolName: 'Computing & Informatics',
    schoolId: 1,
    department: 'Computer Science',
    departmentName: 'Computer Science',
    departmentId: 101,
    academicLevel: 'Masters',
    currentStage: 'final_approval',
    currentStageDisplayName: 'Final Approval',
    status: 'completed',
    statusDisplayName: 'Completed',
    priority: 'high',
    isActive: false,
    isCompleted: true,
    daysInCurrentStage: 3,
    totalDays: 35,
    initiatedByName: 'Dr. Sarah Kimani',
    initiatedByEmail: 'sarah.kimani@must.ac.tz',
    currentAssigneeName: 'Registrar Office',
    currentAssigneeEmail: 'registrar@must.ac.tz',
    submittedDate: '2024-02-10',
    lastUpdated: '2024-03-12',
    actualCompletionDate: '2024-03-12',
    expectedCompletionDate: '2024-03-12',
    proposedEffectiveDate: '2024-09-01',
    proposedExpiryDate: '2027-08-31',
    createdAt: '2024-02-10T07:30:00Z',
    updatedAt: '2024-03-12T15:00:00Z',
    initialNotes: 'Fast-tracked approval due to high demand',
    stages: {
      department_submission: {
        status: 'completed',
        assignedTo: 'Dr. Sarah Kimani',
        startedDate: '2024-02-10',
        completedDate: '2024-02-10',
      },
      school_board_review: {
        status: 'completed',
        assignedTo: 'School Board',
        startedDate: '2024-02-10',
        completedDate: '2024-02-15',
      },
      dean_committee: {
        status: 'completed',
        assignedTo: 'Dean Committee',
        startedDate: '2024-02-15',
        completedDate: '2024-02-20',
      },
      senate_review: {
        status: 'completed',
        assignedTo: 'Senate',
        startedDate: '2024-02-20',
        completedDate: '2024-02-28',
      },
      quality_assurance: {
        status: 'completed',
        assignedTo: 'Quality Assurance',
        startedDate: '2024-02-28',
        completedDate: '2024-03-05',
      },
      cue_submission: {
        status: 'completed',
        assignedTo: 'CUE Submission',
        startedDate: '2024-03-05',
        completedDate: '2024-03-08',
      },
      cue_review: {
        status: 'completed',
        assignedTo: 'CUE Review',
        startedDate: '2024-03-08',
        completedDate: '2024-03-10',
      },
      final_approval: {
        status: 'completed',
        assignedTo: 'Registrar Office',
        startedDate: '2024-03-10',
        completedDate: '2024-03-12',
        feedback: 'Approved and implemented',
      },
    },
  },
  {
    id: 'track-005',
    trackingId: 'TRK-2024-005',
    title: 'Bachelor of Computer Science',
    displayTitle: 'Bachelor of Computer Science',
    displayCode: 'BCS',
    proposedCurriculumName: 'Bachelor of Computer Science (Revised)',
    proposedCurriculumCode: 'BCS',
    proposedDurationSemesters: 8,
    curriculumDescription: 'Updated undergraduate computer science curriculum with modern technologies',
    school: 'Computing & Informatics',
    schoolName: 'Computing & Informatics',
    schoolId: 1,
    department: 'Computer Science',
    departmentName: 'Computer Science',
    departmentId: 101,
    academicLevel: 'Undergraduate',
    currentStage: 'senate_review',
    currentStageDisplayName: 'Senate Review',
    status: 'in_progress',
    statusDisplayName: 'In Progress',
    priority: 'high',
    isActive: true,
    isCompleted: false,
    daysInCurrentStage: 2,
    totalDays: 22,
    initiatedByName: 'Prof. Michael Opiyo',
    initiatedByEmail: 'michael.opiyo@must.ac.tz',
    currentAssigneeName: 'Senate Committee',
    currentAssigneeEmail: 'senate@must.ac.tz',
    submittedDate: '2024-02-20',
    lastUpdated: '2024-03-13',
    expectedCompletionDate: '2024-04-20',
    proposedEffectiveDate: '2024-09-01',
    proposedExpiryDate: '2028-08-31',
    createdAt: '2024-02-20T11:00:00Z',
    updatedAt: '2024-03-13T13:15:00Z',
    initialNotes: 'Curriculum revision to incorporate cloud computing and DevOps',
    stages: {
      department_submission: {
        status: 'completed',
        assignedTo: 'Prof. Michael Opiyo',
        startedDate: '2024-02-20',
        completedDate: '2024-02-20',
      },
      school_board_review: {
        status: 'completed',
        assignedTo: 'School Board',
        startedDate: '2024-02-20',
        completedDate: '2024-02-25',
      },
      dean_committee: {
        status: 'completed',
        assignedTo: 'Dean Committee',
        startedDate: '2024-02-25',
        completedDate: '2024-03-03',
      },
      senate_review: {
        status: 'in_progress',
        assignedTo: 'Senate Committee',
        startedDate: '2024-03-03',
        notes: 'Under review by Senate',
      },
      quality_assurance: {
        status: 'pending',
      },
      cue_submission: {
        status: 'pending',
      },
      cue_review: {
        status: 'pending',
      },
      final_approval: {
        status: 'pending',
      },
    },
  },
  {
    id: 'track-006',
    trackingId: 'TRK-2024-006',
    title: 'MSc Agricultural Economics - Farm Management',
    displayTitle: 'MSc Agricultural Economics - Farm Management',
    displayCode: 'MSAFM',
    proposedCurriculumName: 'MSc Agricultural Economics - Farm Management',
    proposedCurriculumCode: 'MSAFM',
    proposedDurationSemesters: 4,
    curriculumDescription: 'Specialized master program in farm management and agricultural business',
    school: 'Agriculture & Food Science',
    schoolName: 'Agriculture & Food Science',
    schoolId: 2,
    department: 'Agricultural Economics',
    departmentName: 'Agricultural Economics',
    departmentId: 201,
    academicLevel: 'Masters',
    currentStage: 'department_submission',
    currentStageDisplayName: 'Department Submission',
    status: 'pending_review',
    statusDisplayName: 'Pending Review',
    priority: 'medium',
    isActive: true,
    isCompleted: false,
    daysInCurrentStage: 1,
    totalDays: 1,
    initiatedByName: 'Dr. Grace Muthoni',
    initiatedByEmail: 'grace.muthoni@must.ac.tz',
    currentAssigneeName: 'Department Head',
    currentAssigneeEmail: 'depthead@agriculture.must.ac.tz',
    submittedDate: '2024-03-12',
    lastUpdated: '2024-03-13',
    expectedCompletionDate: '2024-05-15',
    proposedEffectiveDate: '2024-09-01',
    proposedExpiryDate: '2027-08-31',
    createdAt: '2024-03-12T14:00:00Z',
    updatedAt: '2024-03-13T09:30:00Z',
    initialNotes: 'New specialization in sustainable farm management',
    stages: {
      department_submission: {
        status: 'in_progress',
        assignedTo: 'Dr. Grace Muthoni',
        startedDate: '2024-03-12',
        notes: 'Recently submitted for review',
        documents: [
          {
            id: 'doc-006',
            originalFilename: 'farm_management_proposal.pdf',
            contentType: 'application/pdf',
            fileSize: 2359296,
            formattedFileSize: '2.2 MB',
            documentType: 'proposal',
            documentTypeDisplayName: 'Curriculum Proposal',
            uploadedByName: 'Dr. Grace Muthoni',
            uploadedAt: '2024-03-12T14:15:00Z',
            uploadedAtFormatted: 'Mar 12, 2024 2:15 PM',
          },
        ],
      },
      school_board_review: {
        status: 'pending',
      },
      dean_committee: {
        status: 'pending',
      },
      senate_review: {
        status: 'pending',
      },
      quality_assurance: {
        status: 'pending',
      },
      cue_submission: {
        status: 'pending',
      },
      cue_review: {
        status: 'pending',
      },
      final_approval: {
        status: 'pending',
      },
    },
  },
]

export const mockTrackingStats = {
  total: mockCurriculumTrackingData.length,
  inProgress: mockCurriculumTrackingData.filter((c) => c.status === 'in_progress').length,
  onHold: mockCurriculumTrackingData.filter((c) => c.status === 'on_hold').length,
  completed: mockCurriculumTrackingData.filter((c) => c.status === 'completed').length,
  overdue: 0,
  myInitiated: mockCurriculumTrackingData.filter((c) => c.initiatedByName === 'Dr. Jane Smith' || c.initiatedByName === 'Prof. James Mwaliko').length,
  myAssigned: mockCurriculumTrackingData.filter((c) => c.currentAssigneeName?.includes('Prof')).length,
  byStatus: {
    completed: mockCurriculumTrackingData.filter((c) => c.status === 'completed').length,
    in_progress: mockCurriculumTrackingData.filter((c) => c.status === 'in_progress').length,
    on_hold: mockCurriculumTrackingData.filter((c) => c.status === 'on_hold').length,
    pending_review: mockCurriculumTrackingData.filter((c) => c.status === 'pending_review').length,
  },
  byStage: {
    department_submission: mockCurriculumTrackingData.filter((c) => c.currentStage === 'department_submission').length,
    school_board_review: mockCurriculumTrackingData.filter((c) => c.currentStage === 'school_board_review').length,
    dean_committee: mockCurriculumTrackingData.filter((c) => c.currentStage === 'dean_committee').length,
    senate_review: mockCurriculumTrackingData.filter((c) => c.currentStage === 'senate_review').length,
    quality_assurance: mockCurriculumTrackingData.filter((c) => c.currentStage === 'quality_assurance').length,
  },
  byPriority: {
    high: mockCurriculumTrackingData.filter((c) => c.priority === 'high').length,
    medium: mockCurriculumTrackingData.filter((c) => c.priority === 'medium').length,
    low: mockCurriculumTrackingData.filter((c) => c.priority === 'low').length,
  },
}

// Mock data for notifications
export const mockNotifications: Notification[] = [
  {
    id: 1,
    type: 'workflow',
    priority: 'high',
    title: 'Curriculum Approval Required',
    message:
      "Computer Science Bachelor's curriculum is pending your approval at the Dean Committee stage.",
    time: '2 minutes ago',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    unread: true,
    urgent: true,
    actions: ['Approve', 'Review', 'Reject'],
  },
  {
    id: 2,
    type: 'reminder',
    priority: 'medium',
    title: 'Site Inspection Scheduled',
    message:
      'Quality Assurance site inspection for Engineering programs scheduled for tomorrow at 10:00 AM.',
    time: '15 minutes ago',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    unread: true,
    urgent: false,
    actions: ['View Details', 'Reschedule'],
  },
  {
    id: 3,
    type: 'system',
    priority: 'low',
    title: 'System Backup Completed',
    message: 'Daily system backup completed successfully. All curriculum data backed up.',
    time: '1 hour ago',
    timestamp: new Date(Date.now() - 60 * 60 * 1000),
    unread: false,
    urgent: false,
    actions: ['View Report'],
  },
  {
    id: 4,
    type: 'alert',
    priority: 'high',
    title: 'Curriculum Expiring Soon',
    message: 'Business Administration curriculum expires in 30 days. Review required.',
    time: '2 hours ago',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    unread: true,
    urgent: true,
    actions: ['Review', 'Extend', 'Archive'],
  },
  {
    id: 5,
    type: 'workflow',
    priority: 'medium',
    title: 'New Curriculum Submitted',
    message:
      'School of Engineering has submitted a new curriculum for Environmental Engineering.',
    time: '3 hours ago',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    unread: false,
    urgent: false,
    actions: ['Review', 'Assign'],
  },
  {
    id: 6,
    type: 'reminder',
    priority: 'high',
    title: 'CUE Review Deadline',
    message:
      'Commission of University Education review response deadline is in 3 days for Medical Sciences curriculum.',
    time: '4 hours ago',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    unread: true,
    urgent: false,
    actions: ['Prepare Response', 'Contact CUE'],
  },
  {
    id: 7,
    type: 'system',
    priority: 'medium',
    title: 'User Access Request',
    message: 'New user registration request from Dr. Sarah Wilson, School of Medicine.',
    time: '5 hours ago',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    unread: false,
    urgent: false,
    actions: ['Approve', 'Review Profile', 'Deny'],
  },
  {
    id: 8,
    type: 'workflow',
    priority: 'low',
    title: 'Committee Meeting Reminder',
    message:
      'Dean Committee meeting scheduled for Friday at 2:00 PM to review pending curricula.',
    time: '1 day ago',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    unread: false,
    urgent: false,
    actions: ['View Agenda', 'Add to Calendar'],
  },
  {
    id: 9,
    type: 'alert',
    priority: 'medium',
    title: 'Duplicate Curriculum Detected',
    message:
      'Potential duplicate curriculum detected: "Information Technology" vs "IT Systems".',
    time: '1 day ago',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    unread: true,
    urgent: false,
    actions: ['Compare', 'Merge', 'Keep Separate'],
  },
  {
    id: 10,
    type: 'system',
    priority: 'low',
    title: 'Monthly Report Generated',
    message: 'Monthly curriculum tracking report for November 2024 is now available.',
    time: '2 days ago',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    unread: false,
    urgent: false,
    actions: ['Download', 'Share', 'Archive'],
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: 1,
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    action: 'UPDATE',
    actionLabel: 'Updated',
    entityType: 'curriculum',
    entityName: 'Bachelor of Science in Computing',
    entityId: 'BSCS-2024',
    performedBy: {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@must.ac.ke',
      role: 'ADMIN',
    },
    changes: [
      {
        field: 'duration',
        oldValue: '4 years',
        newValue: '3.5 years',
      },
      {
        field: 'status',
        oldValue: 'Draft',
        newValue: 'Active',
      },
    ],
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'medium',
    description: 'Curriculum duration and status updated',
  },
  {
    id: 2,
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    action: 'PERMISSION_CHANGE',
    actionLabel: 'Permission Modified',
    entityType: 'user',
    entityName: 'John Doe',
    entityId: 3,
    performedBy: {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@must.ac.ke',
      role: 'ADMIN',
    },
    affectedUser: {
      id: 3,
      name: 'John Doe',
      email: 'john.doe@must.ac.ke',
    },
    changes: [
      {
        field: 'permissions',
        oldValue: 'view_curricula',
        newValue: 'view_curricula, edit_curricula, delete_curricula',
      },
    ],
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'high',
    description: 'User permissions elevated to editor level',
  },
  {
    id: 3,
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    action: 'CREATE',
    actionLabel: 'Created',
    entityType: 'course',
    entityName: 'Introduction to Database Systems',
    entityId: 'CS201',
    performedBy: {
      id: 2,
      name: 'James Mwaliko',
      email: 'james.mwaliko@must.ac.ke',
      role: 'DEAN',
    },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    severity: 'low',
    description: 'New course created successfully',
  },
  {
    id: 4,
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    action: 'DELETE',
    actionLabel: 'Deleted',
    entityType: 'course',
    entityName: 'Obsolete Web Technologies',
    entityId: 'WEB101',
    performedBy: {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@must.ac.ke',
      role: 'ADMIN',
    },
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'warning',
    severity: 'high',
    description: 'Course permanently deleted from system',
  },
  {
    id: 5,
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    action: 'LOGIN',
    actionLabel: 'Logged In',
    entityType: 'user',
    entityName: 'Grace Muthoni',
    entityId: 4,
    performedBy: {
      id: 4,
      name: 'Grace Muthoni',
      email: 'grace.muthoni@must.ac.ke',
      role: 'DEPT_REP',
    },
    ipAddress: '192.168.1.105',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)',
    status: 'success',
    severity: 'low',
    description: 'User successfully authenticated',
  },
  {
    id: 6,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    action: 'EXPORT',
    actionLabel: 'Exported',
    entityType: 'report',
    entityName: 'Curriculum Tracking Report - March 2026',
    entityId: 'RPT-2026-03',
    performedBy: {
      id: 2,
      name: 'James Mwaliko',
      email: 'james.mwaliko@must.ac.ke',
      role: 'DEAN',
    },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'low',
    description: 'Report exported to PDF format',
  },
  {
    id: 7,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    action: 'ROLE_CHANGE',
    actionLabel: 'Role Updated',
    entityType: 'user',
    entityName: 'Peter Kiplagat',
    entityId: 5,
    performedBy: {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@must.ac.ke',
      role: 'ADMIN',
    },
    affectedUser: {
      id: 5,
      name: 'Peter Kiplagat',
      email: 'peter.kiplagat@must.ac.ke',
    },
    changes: [
      {
        field: 'role',
        oldValue: 'DEPT_REP',
        newValue: 'DEAN',
      },
    ],
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'high',
    description: 'User role promoted to Dean',
  },
  {
    id: 8,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    action: 'SYSTEM_SETTING',
    actionLabel: 'System Setting Changed',
    entityType: 'system_setting',
    entityName: 'Email Notifications',
    entityId: 'EMAIL_NOTIF',
    performedBy: {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@must.ac.ke',
      role: 'ADMIN',
    },
    changes: [
      {
        field: 'enabled',
        oldValue: false,
        newValue: true,
      },
      {
        field: 'frequency',
        oldValue: 'daily',
        newValue: 'immediate',
      },
    ],
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'medium',
    description: 'Email notification settings updated',
  },
  {
    id: 9,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    action: 'BULK_OPERATION',
    actionLabel: 'Bulk Operation',
    entityType: 'course',
    entityName: 'Multiple Courses Updated',
    entityId: 'BULK-001',
    performedBy: {
      id: 2,
      name: 'James Mwaliko',
      email: 'james.mwaliko@must.ac.ke',
      role: 'DEAN',
    },
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'medium',
    description: 'Bulk update applied to 15 courses',
    metadata: {
      affectedRecords: 15,
      operation: 'status_update',
    },
  },
  {
    id: 10,
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    action: 'UPDATE',
    actionLabel: 'Updated',
    entityType: 'department',
    entityName: 'Computing & Informatics',
    entityId: 'DEPT-CI',
    performedBy: {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@must.ac.ke',
      role: 'ADMIN',
    },
    changes: [
      {
        field: 'name',
        oldValue: 'Computing and Informatics',
        newValue: 'Computing & Informatics',
      },
    ],
    ipAddress: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    severity: 'low',
    description: 'Department name standardized',
  },
  {
    id: 11,
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000),
    action: 'LOGOUT',
    actionLabel: 'Logged Out',
    entityType: 'user',
    entityName: 'Grace Muthoni',
    entityId: 4,
    performedBy: {
      id: 4,
      name: 'Grace Muthoni',
      email: 'grace.muthoni@must.ac.ke',
      role: 'DEPT_REP',
    },
    ipAddress: '192.168.1.105',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)',
    status: 'success',
    severity: 'low',
    description: 'User session terminated',
  },
  {
    id: 12,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    action: 'UPDATE',
    actionLabel: 'Updated',
    entityType: 'curriculum',
    entityName: 'Bachelor of Arts in English',
    entityId: 'BAE-2024',
    performedBy: {
      id: 2,
      name: 'James Mwaliko',
      email: 'james.mwaliko@must.ac.ke',
      role: 'DEAN',
    },
    changes: [
      {
        field: 'credits',
        oldValue: 120,
        newValue: 132,
      },
    ],
    ipAddress: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'error',
    severity: 'medium',
    description: 'Failed validation - credits exceed department limit',
  },
  {
    id: 13,
    timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000),
    action: 'VIEW',
    actionLabel: 'Viewed',
    entityType: 'curriculum',
    entityName: 'Bachelor of Science in Computing',
    entityId: 'BSCS-2024',
    performedBy: {
      id: 4,
      name: 'Grace Muthoni',
      email: 'grace.muthoni@must.ac.ke',
      role: 'DEPT_REP',
    },
    ipAddress: '192.168.1.105',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)',
    status: 'success',
    severity: 'low',
    description: 'Curriculum document accessed for review',
  },
]

export const mockAuditLogsStats: AuditLogsStats = {
  totalActions: 1547,
  successfulActions: 1487,
  failedActions: 22,
  warningActions: 38,
  criticalActionsToday: 5,
}