import { RecentReportRow } from './RecentReportRow'
import { RECENT_REPORTS } from '@/lib/reports'

export function RecentReportsTable() {
  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-soft p-6">
      <h2 className="text-xl font-semibold text-gray-900 mb-6 flex items-center gap-2">
        <i className="fas fa-history text-must-green" aria-hidden="true" />
        Recently Generated Reports
      </h2>

      <div className="overflow-x-auto">
        <table className="w-full border-collapse" role="table">
          <thead>
            <tr className="bg-gray-50">
              <th
                scope="col"
                className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b border-gray-200"
              >
                Report Name
              </th>
              <th
                scope="col"
                className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b border-gray-200"
              >
                Type
              </th>
              <th
                scope="col"
                className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b border-gray-200"
              >
                Generated By
              </th>
              <th
                scope="col"
                className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b border-gray-200"
              >
                Date
              </th>
              <th
                scope="col"
                className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b border-gray-200"
              >
                Status
              </th>
              <th
                scope="col"
                className="px-4 py-3 text-left text-sm font-semibold text-gray-700 border-b border-gray-200"
              >
                Actions
              </th>
            </tr>
          </thead>
          <tbody>
            {RECENT_REPORTS.map((report) => (
              <RecentReportRow key={report.id} report={report} />
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
